replicaCount: 1

image:
  repository: localhost/eldewrito-server
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add:
      - SYS_PTRACE

resources:
  limits:
    cpu: 1
    memory: 8Gi
  requests:
    cpu: 1
    memory: 3Gi

modSync:
  syncRepo: https://github.com/example/example.com

  image:
    repository: k8s.gcr.io/git-sync
    tag: v3.1.3
    pullPolicy: IfNotPresent
  
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  env: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  extraVolumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
