apiVersion: v1
kind: Service
metadata:
  name: {{ include "eldewrito.fullname" . }}
  labels:
    {{- include "eldewrito.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: game
      protocol: UDP
      port: 11774
      targetPort: 11774
    - name: http
      protocol: TCP
      port: 11775
      targetPort: 11775
    - name: rcon
      protocol: TCP
      port: 11776
      targetPort: 11776
    - name: voip
      protocol: TCP
      port: 11777
      targetPort: 11777
  selector:
    {{- include "eldewrito.selectorLabels" . | nindent 4 }}
